name: Build Clone Website to Docker Tool (Multi-Platform)

permissions:
  contents: write

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: Windows
            distpath: Clone-Website-to-Docker-Tool/dist
            exec_glob: cw2dt.exe
          - os: macos-latest
            platform: macOS-ARM
            distpath: Clone-Website-to-Docker-Tool/dist/cw2dt.app
            exec_glob: cw2dt.app
          - os: macos-13
            platform: macOS-Intel
            distpath: Clone-Website-to-Docker-Tool/dist/cw2dt.app
            exec_glob: cw2dt.app
          - os: ubuntu-latest
            platform: Linux
            distpath: Clone-Website-to-Docker-Tool/dist
            exec_glob: cw2dt

    steps:
      - uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install OS deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          # If you have a requirements.txt, this will use it; otherwise fall back to explicit list.
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install pyinstaller pillow requests beautifulsoup4 lxml PySide6; fi

      - name: Ensure project directories
        run: |
          mkdir -p Clone-Website-to-Docker-Tool/images

      - name: Write PyInstaller spec
        working-directory: Clone-Website-to-Docker-Tool
        shell: bash
        run: |
          cat > cw2dt.spec << 'PYZSPEC'
          # -*- mode: python ; coding: utf-8 -*-
          import os
          from PyInstaller.utils.hooks import collect_submodules
          
          # Data files that actually exist will be included.
          def existing(path): 
              return path if os.path.exists(path) else None

          image_files = []
          for fn in ["images/arrow_right.png","images/docker_logo.png","images/icon.png","images/web_logo.png"]:
              if os.path.exists(fn):
                  image_files.append((fn, "images"))

          datas = []
          if existing("VERSION.txt"):
              datas.append(("VERSION.txt", "."))

          datas += image_files

          hidden = ["PySide6"] + collect_submodules("PySide6")

          a = Analysis(
              ["cw2dt.py"],
              pathex=[],
              binaries=[],
              datas=datas,
              hiddenimports=hidden,
              hookspath=[],
              hooksconfig={},
              runtime_hooks=[],
              excludes=[],
              noarchive=False,
              optimize=0,
          )
          pyz = PYZ(a.pure)

          # Consistent app/binary name everywhere
          exe = EXE(
              pyz,
              a.scripts,
              a.binaries,
              a.datas,
              [],
              name="cw2dt",
              debug=False,
              bootloader_ignore_signals=False,
              strip=False,
              upx=True,
              upx_exclude=[],
              runtime_tmpdir=None,
              console=False,
              disable_windowed_traceback=False,
              argv_emulation=False,
              target_arch=None,
              codesign_identity=None,
              entitlements_file=None,
              icon=("icon.ico" if os.name == "nt" else ("icon.icns" if os.path.exists("icon.icns") else None)),
          )
          PYZSPEC

      - name: Build executable/bundle
        working-directory: Clone-Website-to-Docker-Tool
        run: pyinstaller --noconfirm cw2dt.spec

      # Package per-OS
      - name: Package (Windows)
        if: matrix.platform == 'Windows'
        run: |
          cd Clone-Website-to-Docker-Tool/dist
          zip -j ../../CW2DT-Windows.zip cw2dt.exe ../icon.ico 2>/dev/null || zip -j ../../CW2DT-Windows.zip cw2dt.exe

      - name: Package (Linux)
        if: matrix.platform == 'Linux'
        run: |
          cd Clone-Website-to-Docker-Tool/dist
          chmod +x cw2dt || true
          zip -j ../../CW2DT-Linux.zip cw2dt ../icon.icns 2>/dev/null || zip -j ../../CW2DT-Linux.zip cw2dt

      - name: Package (macOS)
        if: startsWith(matrix.platform, 'macOS')
        run: |
          cd Clone-Website-to-Docker-Tool/dist
          # Zip the .app bundle recursively
          ditto -c -k --sequesterRsrc --keepParent cw2dt.app ../../CW2DT-${{ matrix.platform }}.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CW2DT-${{ matrix.platform }}
          path: |
            CW2DT-${{ matrix.platform }}.zip
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      # Download all platform artifacts into the workspace root
      - uses: actions/download-artifact@v4
        with:
          pattern: CW2DT-*
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            CW2DT-Windows.zip
            CW2DT-macOS-Intel.zip
            CW2DT-macOS-ARM.zip
            CW2DT-Linux.zip
